apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
data:
  containerRuntimeExecutor: emissary
  executor: |
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
  images:
    argoproj/argoexec: {{ .Values.executor.image.repository }}:{{ .Values.executor.image.tag }}
