---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argo-workflows.serverFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-workflows
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-workflows
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: server
    spec:
      serviceAccountName: argo-server
      containers:
        - name: argo-server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          args:
            - server
            - --auth-mode=server
            - --secure=false
          ports:
            - name: web
              containerPort: 2746
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 2746
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-workflows.serverFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
  ports:
    - name: web
      port: {{ .Values.server.service.port }}
      targetPort: web
      protocol: TCP
