apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootUser: {{ .Values.rootUser | quote }}
  rootPassword: {{ .Values.rootPassword | quote }}
