apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
type: Opaque
stringData:
  rootUser: {{ .Values.rootUser | quote }}
  {{- if eq .Values.rootPassword "minioadmin" }}
  rootPassword: {{ randAlphaNum 32 | quote }}
  {{- else }}
  rootPassword: {{ .Values.rootPassword | quote }}
  {{- end }}
