apiVersion: agentic.ninerewards.io/v1alpha1
kind: AgentWorkload
metadata:
  labels:
    app.kubernetes.io/name: agentic-operator
    app.kubernetes.io/managed-by: kustomize
  name: agentworkload-sample
spec:
  # TODO(user): Add fields here
