apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.auth.database | quote }}
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
  POSTGRES_POSTGRES_PASSWORD: {{ .Values.auth.postgresPassword | quote }}
