apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.auth.database | quote }}
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  {{- if eq .Values.auth.password "changeme" }}
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | quote }}
  {{- else }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
  {{- end }}
  {{- if eq .Values.auth.postgresPassword "changeme" }}
  POSTGRES_POSTGRES_PASSWORD: {{ randAlphaNum 32 | quote }}
  {{- else }}
  POSTGRES_POSTGRES_PASSWORD: {{ .Values.auth.postgresPassword | quote }}
  {{- end }}
